{{- if .Values.quay_registry_config_bundle }}
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-registry-config-bundle
  namespace: quay-enterprise
type: Opaque
data:
  config.yaml: |
  {{- .Values.quay_registry_config_bundle | toYaml | trim | nindent 4 }}
{{- end }}
