# https://access.redhat.com/solutions/4910611
{{- if .Values.machineconfig.enabled }}
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    {{- if .Values.runOnInfra }}
    machineconfiguration.openshift.io/role: infra
    {{- else }}
    machineconfiguration.openshift.io/role: worker
    {{- end }}
  name: 01-sebool
spec:
  config:
    ignition:
      version: {{ .Values.machineconfig.ignition_version }}
    systemd:
      units:
      - contents: |
          [Unit]
          Description=Enable container_manage_cgroup on worker nodes
          Before=kubelet.service
          [Service]
          ExecStart=/usr/sbin/setsebool container_manage_cgroup 1
          [Install]
          WantedBy=multi-user.target
        enabled: true
        name: sebool.service
{{- end }}
