{{- if and .Values.operatorGroup.create .Values.subscription.enabled -}}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operatorGroup.name }}
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespaces:
    - {{ .Release.Namespace }}
{{- end }}
