apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tag
  namespace: {{ .Values.application.environments.cicd }}
spec:
  params:
    - name: author
      type: string
    - name: email
      type: string
    - name: revision-type
      type: string
    - name: revision-name
      type: string
  workspaces:
    - name: source
  steps:
    - name: debug
      image: registry.redhat.io/rhel8/nodejs-12@sha256:3c7f0b36e4313819009df28c4b666320e0cff45041ccbc3861327054f9e1d1f6
      workingDir: /workspace/source/{{ .Values.pipeline.build.s2i.context }}
      command: ["/bin/bash", "-c"]
      args:
        - |-
          set -ex
          find /workspace/source/{{ .Values.pipeline.build.s2i.context }}
