name: Validate

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Conftest
        uses: redhat-cop/github-actions/confbatstest@561af5e610560aef3210ca7a08fe73b2add97648 # v4.5
        with:
          tests: _test/conftest.sh
