name: Lint Test

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  lint-test:
    env:
      branch_name: ${{ github.head_ref || github.ref_name }}
      # renovate: datasource=github-releases depName=helm/helm
      HELM_VERSION: v3.17.3
      # renovate: datasource=github-tags depName=python/cpython
      PYTHON_VERSION: v3.13.3
      # renovate: datasource=pypi depName=pybump
      PYBUMP_VERSION: 1.13.2
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0

    - name: Setup Helm 🧰
      uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4
      with:
        version: ${{ env.HELM_VERSION }}

    - name: Setup Python 🐍
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup chart-testing 🧰
      uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

    - name: Setup pybump
      if: ${{ contains(env.branch_name, 'renovate') }}
      run: |
        pip3 install pybump==${PYBUMP_VERSION}

    - name: Bump chart version
      if: ${{ contains(env.branch_name, 'renovate') }}
      id: bumped_charts
      run: |
        .github/renovate-bump.sh

    - name: Run Chart lint tests 🧪
      run: ct lint --target-branch main

    # Use the REST API to commit changes, so we get automatic commit signing
    - name: Push changes
      if: ${{ contains(env.branch_name, 'renovate') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        changed_charts: ${{ steps.bumped_charts.outputs.CHARTS }}
      run: |
        for chart in ${changed_charts}; do
          export SHA=$(git rev-parse origin/${branch_name}:${chart} )

          gh api --method PUT /repos/:owner/:repo/contents/${chart} \
            --field message="chore: bumped ${chart} version" \
            --field content=@<( base64 -i ${chart} ) \
            --field branch="${branch_name}" \
            --field sha="$SHA"
        done
